-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 03/07/2025 às 15:52
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `quiz_ppp`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `perguntas`
--

CREATE TABLE `perguntas` (
  `id` int(11) NOT NULL,
  `pergunta` text NOT NULL,
  `alternativa_a` text NOT NULL,
  `alternativa_b` text NOT NULL,
  `alternativa_c` text NOT NULL,
  `alternativa_d` text NOT NULL,
  `correta` char(1) NOT NULL,
  `ano_edital` int(11) NOT NULL DEFAULT 2024,
  `numero_edital` varchar(20) NOT NULL DEFAULT '001/2024',
  `temas` text NOT NULL DEFAULT 'Tema não especificado',
  `sub_temas` text NOT NULL DEFAULT 'Subtema não especificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `perguntas`
--

INSERT INTO `perguntas` (`id`, `pergunta`, `alternativa_a`, `alternativa_b`, `alternativa_c`, `alternativa_d`, `correta`, `ano_edital`, `numero_edital`, `temas`, `sub_temas`) VALUES
(1, 'Qual é a missão principal da ESP segundo o PPP?', 'Emitir diplomas para profissionais da saúde', 'Promover saúde com ações curativas', 'Contribuir para a formação e qualificação dos trabalhadores do SUS', 'Fiscalizar unidades de saúde', 'C', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(2, 'Segundo o\r\nPPP/ESP/CE-2024-2027, qual é a abordagem\r\npedagógica prioritária para o desenvolvimento\r\ndas ações formativas?', 'Ensino tradicional centrado na transmissão de conteúdo', 'Educação baseada em competências, com ênfase na aprendizagem ativa e contextualizada', 'Ensino exclusivamente teórico, sem práticas de campo.', 'Educação baseada em métodos expositivos e avaliações sumativas.', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(3, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é o papel da\r\navaliação institucional no processo de\r\nimplementação do projeto pedagógico?', 'Ser utilizada apenas para fins de classificação dos estudantes', 'Monitorar, avaliar e promover melhorias contínuas na formação e na gestão da escola', 'Ser realizada apenas ao final do ciclo de formação, sem impacto nas ações pedagógicas', 'Ser exclusiva para avaliação dos professores, sem envolver estudantes ou gestores.', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(4, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é o princípio\r\nnorteador para a elaboração das ações\r\npedagógicas na Escola de Saúde Pública do\r\nCeará?\r\n', 'A centralidade na transmissão de conhecimentos teóricos.', 'A integração entre teoria e prática, promovendo a formação contextualizada.', 'A priorização de atividades administrativas e burocráticas.', 'A segregação entre ensino, pesquisa e extensão, mantendo-os isolados', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(5, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual estratégia é\r\npriorizada para garantir a formação\r\ncontinuada dos docentes na Escola de Saúde\r\nPública do Ceará?', 'Oferecer cursos de curta duração sem relação com as demandas do SUS.', 'Promover programas de formação continuada alinhados às necessidades do sistema de saúde.', 'Manter os docentes em formação apenas no início da carreira, sem ações posteriores.', 'Priorizar atividades administrativas em detrimento do desenvolvimento profissional docente.', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(6, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é a principal\r\nestratégia para promover a integração entre\r\nensino, pesquisa e extensão na Escola de\r\nSaúde Pública do Ceará?', 'Manter essas atividades isoladas para garantir foco específico.', 'Promover ações integradas que articulam ensino, pesquisa e extensão de forma contínua e contextualizada.', 'Priorizar apenas a pesquisa, relegando o ensino e a extensão a um segundo plano', 'Limitar a participação dos estudantes nas atividades de extensão para evitar dispersão.', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(7, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é a abordagem\r\nprioritária para a formação de profissionais de\r\nsaúde na perspectiva de integralidade e\r\natenção básica?', ' Focar exclusivamente na formação técnica especializada, sem integração com a atenção básica.', 'Promover uma formação que valorize a integralidade, a atenção primária e a interdisciplinaridade, articulando teoria e prática.', 'Priorizar atividades administrativas e burocráticas, relegando a prática clínica.', 'Concentrar a formação apenas em ambientes acadêmicos, sem contato com os serviços de saúde.', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(8, 'Considerando a seção do\r\nPPP/ESP/CE-2024-2027 que trata da\r\navaliação institucional e seu papel no\r\naprimoramento contínuo da ESP-CE, qual das\r\nseguintes abordagens metodológicas\r\ndemonstra maior aderência aos princípios de\r\numa avaliação formativa e participativa,\r\nconforme preconizado no documento?\r\n', 'Aplicação de questionários padronizados ao final de cada ciclo formativo, com foco em indicadores quantitativos de desempenho discente.', 'Implementação de um sistema de acompanhamento individualizado do progresso dos estudantes, baseado em portfólios e autoavaliações supervisionadas.', 'Realização de reuniões periódicas com representantes de diferentes segmentos da comunidade acadêmica para análise qualitativa dos processos e resultados, culminando na elaboração de planos de melhoria consensuais.', 'Utilização de provas objetivas somativas, com o objetivo de classificar os estudantes e identificar lacunas de aprendizagem em nível macroinstitucional.', 'c', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(9, 'O PPP/ESP/CE-2024-2027\r\nenfatiza a importância da integração\r\ncurricular e da interdisciplinaridade como\r\neixos estruturantes dos processos formativos.\r\nQual das seguintes iniciativas pedagógicas\r\nrepresenta a aplicação mais efetiva desses\r\nprincípios?\r\n', ' Organização dos conteúdos disciplinares em módulos estanques, com avaliações separadas para cada disciplina.', 'Desenvolvimento de projetos de intervenção na realidade social e de saúde, envolvendo diferentes áreas do conhecimento e a participação ativa dos estudantes.', 'Utilização de metodologias ativas de ensino-aprendizagem em disciplinas específicas, mantendo a estrutura curricular tradicional', 'Oferta de disciplinas eletivas que abordam temas transversais, permitindo que os estudantes complementem sua formação de forma individualizada.', 'b', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(10, 'Considerando o eixo\r\nestratégico de &quot;Gestão e Avaliação da\r\nFormação&quot; presente no\r\nPPP/ESP/CE-2024-2027, qual das seguintes\r\nações representa a abordagem mais alinhada\r\ncom a proposta de avaliação formativa e\r\ncontinuada dos processos educativos, visando\r\no aprimoramento constante das ofertas\r\nformativas da Escola?\r\n', 'A aplicação de provas objetivas ao final de cada módulo ou curso, com o objetivo de classificar os participantes e identificar aqueles que atingiram o desempenho mínimo esperado.', 'A implementação de um sistema de coleta de feedback dos participantes ao final de cada atividade educativa, utilizando questionários padronizados com foco na satisfação com o conteúdo e os facilitadores.', 'O desenvolvimento de instrumentos de avaliação diversificados que incluam a autoavaliação dos participantes, a avaliação por pares, a análise de portfólios e a observação de práticas, integrados ao longo do processo formativo para fornecer insights para ajustes pedagógicos.', 'A realização de avaliações externas periódicas por órgãos competentes, com o objetivo de certificar a qualidade das ofertas formativas da Escola em relação a padrões nacionais e internacionais.', 'c', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(11, 'Considerando o eixo\r\nestratégico de &quot;Gestão e Avaliação da\r\nFormação&quot; presente no\r\nPPP/ESP/CE-2024-2027, qual das seguintes\r\nações representa a abordagem mais alinhada\r\ncom a proposta de avaliação formativa e\r\ncontinuada dos processos educativos, visando\r\no aprimoramento constante das ofertas\r\nformativas da Escola?\r\n', 'A aplicação de provas objetivas ao final de cada módulo ou curso, com o objetivo de classificar os participantes e identificar aqueles que atingiram o desempenho mínimo esperado.', 'A implementação de um sistema de coleta de feedback dos participantes ao final de cada atividade educativa, utilizando questionários padronizados com foco na satisfação com o conteúdo e os facilitadores.', 'O desenvolvimento de instrumentos de avaliação diversificados que incluam a autoavaliação dos participantes, a avaliação por pares, a análise de portfólios e a observação de práticas, integrados ao longo do processo formativo para fornecer insights para ajustes pedagógicos.', 'A realização de avaliações externas periódicas por órgãos competentes, com o objetivo de certificar a qualidade das ofertas formativas da Escola em relação a padrões nacionais e internacionais.', 'c', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(12, 'Considerando o eixo\r\nestratégico de &quot;Gestão e Avaliação da\r\nFormação&quot; presente no\r\nPPP/ESP/CE-2024-2027, qual das seguintes\r\nações representa a abordagem mais alinhada\r\ncom a proposta de avaliação formativa e\r\ncontinuada dos processos educativos, visando\r\no aprimoramento constante das ofertas\r\nformativas da Escola?\r\n', 'A aplicação de provas objetivas ao final de cada módulo ou curso, com o objetivo de classificar os participantes e identificar aqueles que atingiram o desempenho mínimo esperado.', 'A implementação de um sistema de coleta de feedback dos participantes ao final de cada atividade educativa, utilizando questionários padronizados com foco na satisfação com o conteúdo e os facilitadores.', 'O desenvolvimento de instrumentos de avaliação diversificados que incluam a autoavaliação dos participantes, a avaliação por pares, a análise de portfólios e a observação de práticas, integrados ao longo do processo formativo para fornecer insights para ajustes pedagógicos.', 'A realização de avaliações externas periódicas por órgãos competentes, com o objetivo de certificar a qualidade das ofertas formativas da Escola em relação a padrões nacionais e internacionais.', 'c', 2024, '001', 'Tema não especificado', 'Subtema não especificado'),
(13, 'Considerando a Lei Federal nº\r\n8.080/1990, que regula as ações e serviços de\r\nsaúde no Brasil, assinale a afirmativa que\r\nreflete um dos objetivos fundamentais do\r\nSistema Único de Saúde (SUS)', 'priorizar a assistência direta aos indivíduos, com ações pontuais e não prioritárias de prevenção e promoção da saúde.', 'o grande foco é a recuperação da saúde, com destinação de poucos esforços para a prevenção de doenças e promoção da saúde.', 'a identificação dos fatores determinantes da saúde ocorre de forma contínua sem a inclusão de formulação de políticas de saúde em seus objetivos.', 'oca em garantir a assistência às pessoas por meio de ações abrangentes de promoção, proteção e recuperação da saúde, integrando tanto serviços assistenciais quanto ações preventivas', 'D', 2024, '008', 'Lei Federal nº 8.080/1990', 'Subtema não especificado'),
(14, '“De acordo com os princípios e\r\ndiretrizes do SUS, assinale a alternativa que\r\nmelhor se enquadra na definição a seguir:\r\n“Significa garantir que todos tenham acesso\r\nigualitário aos serviços de saúde, priorizando\r\nas necessidades daqueles que mais precisam,\r\nsem discriminação ou favorecimento injusto.\r\nIsso implica em distribuir recursos de forma\r\njusta e proporcionar atenção integral e\r\nuniversal, considerando as diferenças\r\nindividuais e coletivas da população\r\nbrasileira.”\r\n', 'equidade.', 'integralidade.', 'resolutividade.', 'universalidade.', 'A', 2024, '008', 'Princípios do SUS – Equidade', 'Subtema não especificado'),
(15, 'A hierarquização no Sistema de\r\nSaúde faz parte de um princípio básico. Nesse\r\nsentido, assinale a alternativa que descreva a\r\nhierarquia do Sistema Único de Saúde (SUS).', 'deve existir uma análise da idade dos pacientes para promover os serviços e realizar o atendimento com base na prioridade.', 'as ações e os serviços oferecidos pelo sistema devem respeitar os níveis de complexidade: primário, secundário e terciário.', 'a hierarquia discorre sobre os médicos possuírem um nível de superioridade em relação aos enfermeiros, e que a decisão do médico deve sempre prevalecer.', 'as ações e os serviços oferecidos pelo sistema não devem respeitar os níveis de complexidade, ou seja, o paciente pode ser atendido em qualquer nível de atenção independentemente da sua necessidade.', 'B', 2024, '008', 'Organização do SUS – Níveis de Atenção e Hierarquização', 'Subtema não especificado'),
(16, 'Um grupo de profissionais,\r\ninteressados em ingressar na Escola de Saúde\r\nPública do Ceará (ESP/Ce), estava discutindo\r\ncomo esta instituição foi criada. Dentre as\r\nopções abaixo, marque a correta.\r\nA ESP/Ce foi criada:', 'em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Universidade Federal do Ceará (UFC) e da Universidade Estadual do Ceará (UECE).', 'em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Federal do Ceará (UFC).', 'em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Estadual do Ceará (UECE)', 'em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Escola Nacional de Saúde Pública (ENSP)', 'B', 2024, '008', 'História da ESP/CE', 'Subtema não especificado'),
(17, 'Estudando o histórico da\r\nEscola de Saúde Pública do Ceará (ESP/Ce),\r\num grupo de profissionais percebeu que o\r\nobjetivo do projeto de sua criação foi:', 'ser uma instituição destinada para a formação dos servidores da Secretaria da Saúde do Estado do Ceará (SESA) nos aspectos relacionados à saúde pública e do SUS.', 'proporcionar aos profissionais da saúde o acesso à formação e capacitação de modo a desenvolver as competências para a operacionalização das suas atividades no âmbito do SUS.', 'ser uma instituição acadêmica vinculada à Secretaria da Saúde do Estado do Ceará (SESA) para a formação e qualificação de seus servidores, oportunizando cursos de mestrado e doutorado.', 'proporcionar aos profissionais da saúde o acesso à graduação e educação continuada de modo a desenvolver os conhecimentos necessários para a operacionalização das atividades no âmbito do SUS.', 'B', 2024, '008', 'Missão e Objetivo Institucional da ESP/CE', 'Subtema não especificado'),
(20, 'Dois autores fundamentam os\r\npressupostos filosóficos do Projeto Político\r\nPedagógico da ESP/Ce. São eles:', 'John Dewey e Paulo Freire', 'Jerome Bruner e Lev Vygotsky', 'Maria Montessori e Paulo Freire', 'Anísio Teixeira e Darcy Ribeiro', 'A', 2024, '008', 'PPP da ESP/CE', 'Subtema não especificado'),
(21, 'O PPP vigente da ESP/CE e,\r\ndisponível em sua página, estabelece que uma\r\nde suas premissas educacionais é orientar e\r\nbasear na comunidade o currículo de seus\r\nProgramas. Isso significa que:', 'durante a elaboração da justificativa do currículo do Programa é obrigatória a presença de representantes da comunidade e profissionais de saúde que atuam em ambiente comunitário.', 'no desenho do currículo do Programa devem ser levadas em conta as necessidades da comunidade e previstas atividades educacionais no ambiente comunitário.', ' a maior parte da execução do Programa seja em ambientes comunitários e serviços de atenção básica à saúde.', 'o desenho do currículo seja feito por especialistas em saúde comunitária ou em saúde coletiva.', 'b', 2024, '009', 'PPP da ESP/CE', 'Subtema não especificado'),
(22, 'Alguns professores da ESP/CE\r\nforam encarregados para elaborar um Curso\r\nde Especialização. Dentre as alternativas\r\nabaixo, assinale a que melhor expressa,\r\ncronologicamente, algumas das etapas da\r\nelaboração do currículo do curso, segundo\r\norientações do PPP vigente:', 'análise da potencial clientela, elaboração da justificativa do curso, elaboração das competências e objetivos de aprendizagem, construção da matriz curricular.', 'definição dos conteúdos, elaboração dos objetivos de aprendizagem, definição das competências a serem desenvolvidas e escolha dos métodos de ensino e avaliação.', 'elaboração da justificativa do curso, análise da potencial clientela, elaboração das competências e objetivos de aprendizagem, escolha dos métodos de ensino e avaliação.', 'definição das competências a serem desenvolvidas, definição dos conteúdos, elaboração dos objetivos de aprendizagem e escolha dos métodos de ensino e avaliação.', 'c', 2024, '009', 'PPP da ESP/CE', 'Subtema não especificado'),
(23, 'O coordenador de um\r\nPrograma de Especialização da ESP/CE\r\nprocurou assessoria educacional para utilizar a\r\nAprendizagem Baseada em Problemas\r\n(Problem Based Learning – PBL) como\r\nmetodologia ativa no curso.\r\nSegundo o PPP vigente da ESP/CE, o PBL:', ' é uma metodologia ativa de aprendizagem baseada na análise e resolução de problemas, em pequenos grupos, com o suporte de um facilitador.', ' é uma metodologia ativa de aprendizagem na qual o professor/facilitador dá aulas em pequenos grupos utilizando uma situação-problema.', 'também conhecido no Brasil como Metodologia da Problematização, utiliza sete passos durante os grupos tutoriais.', 'é uma metodologia ativa de aprendizagem que utiliza como técnica de ensino o Arco de Maguerez.', 'a', 2024, '009', 'PPP da ESP/CE', 'Subtema não especificado'),
(24, 'Estudando o histórico da\r\nEscola de Saúde Pública do Ceará (ESP/Ce),\r\num grupo de profissionais percebeu que o\r\nobjetivo do projeto de sua criação foi:', 'Ser uma instituição destinada para a formação dos servidores da Secretaria da Saúde do Estado do Ceará (SESA) nos aspectos relacionados à saúde pública e do SUS.', 'Proporcionar aos profissionais da saúde o acesso à formação e capacitação de modo a desenvolver as competências para a operacionalização das suas atividades no âmbito do SUS.', 'Ser uma instituição acadêmica vinculada à Secretaria da Saúde do Estado do Ceará (SESA) para a formação e qualificação de seus servidores, oportunizando cursos de mestrado e doutorado.', 'Proporcionar aos profissionais da saúde o acesso à graduação e educação continuada de modo a desenvolver os conhecimentos necessários para a operacionalização das atividades no âmbito do SUS.', 'a', 2024, '011', 'PPP da ESP/CE', 'Subtema não especificado'),
(25, 'Considerando o processo de\r\ndesenvolvimento histórico da Escola de Saúde\r\nPública do Ceará - ESP/CE, marque a assertiva\r\ncorreta.', ' Foi criada em 1990, a partir da sanção da Lei nº 12.140, sob a forma de autarquia, vinculada à Secretaria de Saúde do Estado do Ceará', 'Compõe a Rede das Escolas Técnicas do SUS (RET-SUS) e está entre as 20 escolas existentes no país. Isso porque, desde a sua criação, tem como um de seus focos de atenção a formação na área da Educação básica.', 'Outro marco histórico foi o lançamento da revista Cadernos ESP, uma publicação anual, voltada para atender as necessidades do SUS e divulgar pesquisas em saúde coletiva e educação, no âmbito estadual.', 'Foi estabelecida com o propósito de promover ações voltadas à pesquisa, informação, documentação em saúde pública, educação continuada, capacitação e aperfeiçoamento dos profissionais do Sistema Único de Saúde estadual.', 'd', 2024, '011', 'História da ESP/CE', 'Subtema não especificado'),
(26, 'A missão, visão e os valores\r\norganizacionais da ESP/CE foram revistos e\r\natualizados durante o Planejamento\r\nEstratégico. Desta forma, depreende-se que,\r\natualmente, representam a intenção\r\nestratégica, o pensamento sistêmico que\r\ninfluenciam e direcionam a execução das\r\nações da Instituição. Logo:', 'Tem como missão promover o desenvolvimento de excelência da força de trabalho em Saúde por meio da Educação Permanente, apoiado pela ciência, inovação e tecnologia, visando o fortalecimento do SUS e a melhoria da qualidade de vida das pessoas.', 'Tem por missão promover a educação, o conhecimento e a inovação, contribuindo para a saúde individual e coletiva, além da melhoria da qualidade de vida e felicidade das pessoas', 'Tem como visão o comprometimento com o SUS; Eficiência e sustentabilidade; Ética; Valores Humanização; Inclusão e diversidade; Inovação e conhecimento; Transparência; Valorização das pessoas', 'Tem como valores a busca pelo reconhecimento da excelência na educação e formação de qualificação da força de trabalho para o Sistema Único de Saúde.', 'a', 2024, '011', 'Missão e Objetivo Institucional da ESP/CE', 'Subtema não especificado'),
(27, 'A missão, visão e os valores\r\norganizacionais da ESP/CE foram revistos e\r\natualizados durante o Planejamento\r\nEstratégico. Desta forma, depreende-se que,\r\natualmente, representam a intenção\r\nestratégica, o pensamento sistêmico que\r\ninfluenciam e direcionam a execução das\r\nações da Instituição. Logo:', 'Tem como missão promover o desenvolvimento de excelência da força de trabalho em Saúde por meio da Educação Permanente, apoiado pela ciência, inovação e tecnologia, visando o fortalecimento do SUS e a melhoria da qualidade de vida das pessoas.', 'Tem por missão promover a educação, o conhecimento e a inovação, contribuindo para a saúde individual e coletiva, além da melhoria da qualidade de vida e felicidade das pessoas', 'Tem como visão o comprometimento com o SUS; Eficiência e sustentabilidade; Ética; Valores Humanização; Inclusão e diversidade; Inovação e conhecimento; Transparência; Valorização das pessoas', 'Tem como valores a busca pelo reconhecimento da excelência na educação e formação de qualificação da força de trabalho para o Sistema Único de Saúde.', 'a', 2024, '011', 'Missão e Objetivo Institucional da ESP/CE', 'Subtema não especificado'),
(28, 'Em dezembro de 2020, com\r\nbase no diagnóstico situacional da saúde da\r\npopulação cearense e da estrutura dos\r\nequipamentos da Rede Sesa, foi lançado pela\r\nESP/CE um projeto com uma de suas\r\nfinalidades regionalizar as vagas dos\r\nProgramas de Residências em Saúde,\r\nfortalecendo as Redes de Atenção à Saúde de\r\nacordo com as necessidades regionais. Que\r\nação foi essa?', 'Programa de Valorização dos Supervisores de Residências em Saúde.', 'Projeto Ampliares.', ' Projeto de Interiorização de Residências em Saúde (PIRS).', 'Programa de Valorização dos Preceptores de Residências em Saúde', 'b', 2024, '011', 'PIRS', 'Subtema não especificado'),
(29, 'O Decreto nº 35.344, de 22\r\nde junho de 2023, e o Decreto nº 35.750, de\r\n10 de novembro de 2023, alteram a estrutura\r\norganizacional da ESP/CE, que passou a ser\r\ncomposta por:', 'Superintendência, Assessorias, Diretorias e Gerências.', 'Diretoria Geral, Coordenadorias, Assessorias e Gerências.', 'Superintendência, Diretorias, Assessorias e Núcleos.', 'Diretoria Geral, Coordenadorias, Assessorias e Centros.', 'a', 2024, '011', 'Estrutura organizacional da ESP/CE – decretos de 2023', 'Subtema não especificado'),
(30, 'Um grupo de profissionais,\r\ninteressados em ingressar na Escola de Saúde\r\nPública do Ceará (ESP/Ce), estava discutindo\r\ncomo esta instituição foi criada. Dentre as\r\nopções abaixo, marque a correta. A ESP/Ce foi\r\ncriada:', 'Em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Universidade Federal do Ceará (UFC) e da Universidade Estadual do Ceará (UECE).', 'Em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Federal do Ceará (UFC)', 'Em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Estadual do Ceará (UECE)', 'Em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Escola Nacional de Saúde Pública (ENSP).', 'b', 2024, '011', 'História da ESP/CE', 'Subtema não especificado'),
(31, 'Em um contexto de\r\ndesenvolvimento web, considerando o uso de\r\nframeworks, qual das opções descreve\r\ncorretamente uma vantagem do seu uso?', 'Aumento da complexidade do código devido à padronização forçada.', 'Diminuição da produtividade da equipe de desenvolvimento devido à curva de aprendizado.', 'Aumento das opções de personalização devido à flexibilidade oferecida pelo framework.', 'Facilidade na implementação de funcionalidades comuns devido à reutilização de código e convenções estabelecidas.', 'd', 2024, '011', 'Tecnologia / Desenvolvimento', 'Subtema não especificado'),
(32, 'Em um cenário de rápido\r\ncrescimento tecnológico e demandas cada vez\r\nmais complexas, os frameworks de\r\narquitetura surgem como resposta à\r\nnecessidade de padronização e organização no\r\ndesenvolvimento de sistemas distribuídos,\r\nvisando facilitar a escalabilidade, a\r\ninteroperabilidade e a manutenção em\r\nambientes heterogêneos e dinâmicos.\r\nAssinale a opção que indica características de\r\num framework de arquitetura', 'Os frameworks de arquitetura são estruturas conceituais ou um conjunto de estruturas, para desenvolvimento, implementação e manutenção de uma arquitetura.', 'Esses frameworks ampliam a complexidade do desenvolvimento incremental da arquitetura e descrevem convenções e práticas de arquitetura em comunidades e domínios de aplicação.', 'Esses frameworks obrigatoriamente incluem descrições de aspectos de interesse e escopo da arquitetura a ser desenvolvida.', 'Os frameworks de arquitetura podem ser usados em contexto específico de processos que facilitam a comunicação entre projetos.', 'a', 2024, '011', 'Tecnologia / Desenvolvimento', 'Tecnologia / Desenvolvimento'),
(33, 'O desenvolvimento orientado a\r\ntestes (TDD):', ' é um conjunto de técnicas que se associam ao X P (extreme programming) para o desenvolvimento incremental do código que se inicia com os testes.', 'agrega um conjunto de testes de integração para avaliar a interconexão dos componentes do software com as aplicações a ele relacionadas.', ' avalia o desempenho do desenvolvimento de sistemas verificando se o volume de acessos/transações está acima da média esperada.', 'averiguar se o sistema atende aos requisitos de desempenho verificando se o volume de acessos/transações se mantém dentro do esperado.', 'a', 2024, '011', 'Desenvolvimento orientado a testes (TDD)', 'Tecnologia / Desenvolvimento'),
(34, 'Em um sistema baseado em\r\nmicroservices, qual das seguintes opções é\r\numa desvantagem em relação a uma\r\narquitetura monolítica?', 'A dificuldade em escalar a aplicação horizontalmente', 'A complexidade na gestão e monitoramento de múltiplos serviços independente', 'A necessidade de reescrever todo o código para introduzir uma nova funcionalidade.', 'A dependência de um único banco de dados centralizado para todas as operações.', 'B', 2024, '011', 'microservices', 'Tecnologia / Desenvolvimento'),
(35, 'O código limpo, ou clean code,\r\né um estilo de programação que enfatiza a\r\nlegibilidade, a facilidade de manutenção e a\r\neficiência do código. O objetivo é:', ' escrever código que seja fácil de entender e complexo de editar o que facilita a colaboração entre membros da equipe e reduz a incidência de problemas (bugs).', ' escrever código que seja fácil de entender e fácil de editar o que facilita a colaboração entre membros da equipe, no entanto aumenta a incidência de problemas (bugs).', ' escrever código que seja complexo de entender e de editar para evitar a incidência de problemas (bugs).', 'O objetivo é escrever código que seja fácil de entender e modificar, o que facilita a colaboração entre membros da equipa e reduz a incidência de problemas (bugs).', 'D', 2024, '011', 'Código Limpo/ Clean Code', 'Tecnologia / Desenvolvimento'),
(36, 'Em relação aos princípios de\r\nClean Code, qual das seguintes práticas é mais\r\nimportante para garantir que o código seja\r\nlegível e fácil de manter por outros\r\ndesenvolvedores?', 'Utilizar nomes de variáveis e funções que descrevam claramente sua finalidade e comportamento.', ' Escrever o código de forma a minimizar o número de linhas, mesmo que a legibilidade seja comprometida.', ' Incluir comentários extensivos para explicar cada linha de código.', 'Focar em otimização prematura para melhorar o desempenho em detrimento da clareza do código.', 'A', 2024, '011', 'Código Limpo/ Clean Code', 'Tecnologia / Desenvolvimento'),
(37, 'Em relação a segurança da\r\nlinguagem javascript no lado do cliente na\r\ncondição padrão de defesa dos navegadores\r\nweb, é permitido:', 'gravar arquivos arbitrários no computador do cliente', 'configurar a propriedade value do HTML file upload.', 'listar diretórios arbitrários no computador do cliente.', 'fechar janelas do navegador abertas pelo javascript.', 'D', 2024, '011', 'JavaScript', 'Tecnologia / Desenvolvimento'),
(38, 'Na linguagem javascript, são\r\nutilizadas palavras em um mecanismo para\r\ntratamento de exceções:', 'try, catch e except', 'catch, throw e except', 'try e except', 'try, catch e finally.', 'D', 2024, '011', 'JavaScript', 'Tecnologia / Desenvolvimento'),
(39, 'Na linguagem JavaScript\r\nquando o valor de uma variável é declarado,\r\nmas ela não possui nenhum valor concreto\r\narmazenado, como por exemplo em um\r\nelemento array que não existe, é retornado:', ' string 0.', 'objeto global.', ' Null', 'indefinido.', 'd', 2024, '011', 'JavaScript', 'Tecnologia / Desenvolvimento'),
(40, 'Sobre a tecnologia WEB do\r\nJavascript (JS), para inserir códigos JS em um\r\ndocumento HTML, é necessário o uso de uma\r\ntag específica para isso. A qual tag abaixo o\r\ntrecho se refere?', '<html> conteúdo </html>', '<head> conteúdo </head>', '<inputJS> conteúdo </ inputJS >', '<script> conteúdo </script>', 'd', 2024, '011', 'JavaScript', 'Tecnologia / Desenvolvimento'),
(41, 'Para que uma API seja\r\nreconhecida como RESTful, ela deve atender a\r\nalguns critérios adicionais aos princípios\r\nREST. Entre esses critérios está a interface\r\nuniforme, que pode ser obtida', ' pela garantia de que será fornecido o mesmo resultado pelo servidor, independentemente de quantas vezes for requisitado recurso.', 'pelas informações completas e necessárias fornecidas pelo cliente para que o servidor entenda e processe a requisição.', 'pela identificação de recursos em requisições de forma única', ' pelos depósitos temporários (cache) dos resultados retornados pelo servidor', 'c', 2024, '011', 'RESTful', 'Tecnologia / Desenvolvimento'),
(42, 'Nos métodos ágeis XP e Scrum,\r\nas entregas de partes funcionais do projeto\r\nsão divididas em ciclos, geralmente\r\ncompreendidos no período de 1 a 4 semanas.\r\nEstes ciclos denominam-se, respectivamente,\r\n', 'iterações e sprint.', 'reunião de planejamento e backlog.', 'período de entrega e reunião de revisão.', 'backlog e planejamento da produção.', 'a', 2024, '011', 'Métodos ágeis', 'Tecnologia / Desenvolvimento'),
(43, 'Assinale a alternativa que\r\napresenta corretamente uma metodologia ágil\r\npara a gestão e planejamento de projetos de\r\nsoftware.', 'Scrum', 'Ciclo de Vida', 'RUP – Rational Unified Process', 'Ferramentas CASE', 'a', 2024, '011', 'Métodos ágeis', 'Tecnologia / Desenvolvimento'),
(44, 'Assinale a alternativa correta\r\nconsiderando as responsabilidades e os papéis\r\nna metodologia SCRUM.', 'O responsável por gerenciar o Product Backlog (garantindo que esteja visível para todos), gerar e disseminar os requisitos do projeto, assim como o plano para as entregas sucessivas, priorizando os resultados que trarão maior valor agregado ao projeto, é o Product Owner.', 'O responsável por implementar o método Scrum, assim como por ensiná-lo a todos os envolvidos nos projetos e assegurar que todos sigam as suas regras e práticas é denominado Time Scrum.', 'O grupo de desenvolvedores que é coletivamente responsável pelo sucesso de cada iteração e do projeto como um todo é conhecido como Scrum Masters.', 'O grupo de gerentes com responsabilidade de avaliar os custos do projeto é denominado Scrum Cost.', 'a', 2024, '011', 'Métodos ágeis', 'Tecnologia / Desenvolvimento'),
(45, 'Durante uma revisão de código\r\n(code review), qual é o principal objetivo ao\r\nrevisar a lógica implementada por um\r\ndesenvolvedor?', 'Identificar inconsistências visuais na interface do usuário', 'Verificar se o código segue os padrões de nomenclatura da equipe', 'Garantir que a lógica do código seja correta e eficiente, evitando bugs.', 'Avaliar a complexidade das ferramentas de automação utilizadas', 'c', 2024, '011', 'Métodos ágeis', 'Tecnologia / Desenvolvimento'),
(46, 'Qual tipo de teste de software\r\né realizado para garantir que uma única\r\nfunção ou método do código esteja\r\nfuncionando corretamente, de forma isolada?\r\n', 'Teste de integração', 'Teste funcional', 'Teste unitário', 'Teste de desempenho', 'c', 2024, '011', 'testes (TDD)', 'Tecnologia / Desenvolvimento'),
(47, 'Em um projeto de software, o\r\nteste de integração é realizado para:', 'Verificar o desempenho do sistema sob carga extrema.', 'Avaliar a funcionalidade de interfaces gráficas do usuário.', 'Garantir que diferentes módulos do sistema funcionem bem juntos.', 'Testar individualmente as menores unidades de código.', 'c', 2024, '011', 'testes (TDD)', 'Tecnologia / Desenvolvimento'),
(48, 'Quando um time de QA realiza\r\ntestes funcionais em um software, qual é o\r\nprincipal foco desses testes?\r\n', 'Avaliar a usabilidade da interface do usuário.', 'Verificar a performance do sistema sob condições de pico.', 'Garantir que as funcionalidades do sistema correspondam aos requisitos especificados', 'Analisar o consumo de recursos de hardware durante a execução do software.', 'c', 2024, '011', 'testes (TDD)', 'Tecnologia / Desenvolvimento'),
(49, 'Durante a fase de testes de\r\ndesempenho, qual aspecto do software é mais\r\nfrequentemente avaliado?\r\n', 'A capacidade do software de executar todas as funcionalidades planejadas.', 'A velocidade e estabilidade do software sob diferentes cargas de uso.', 'A integração correta entre diferentes módulos e componentes.', 'A clareza e a qualidade do código fonte escrito pelos desenvolvedores.', 'B', 2024, '011', 'testes (TDD)', 'Tecnologia / Desenvolvimento'),
(50, 'Uma empresa de tecnologia\r\nestá desenvolvendo um novo aplicativo de\r\ncomércio eletrônico e está considerando\r\nutilizar uma arquitetura monolítica. Qual das\r\nseguintes afirmações melhor descreve uma\r\ncaracterística dessa abordagem?', 'Cada funcionalidade do aplicativo é desenvolvida e mantida como um serviço independente.', 'Todo o código da aplicação é integrado em um único código base, facilitando a implantação.', 'A escalabilidade horizontal é simples, permitindo o crescimento modular do sistema.', 'A comunicação entre componentes ocorre exclusivamente por meio de APIs RESTful.', 'b', 2024, '011', 'Arquitetura monolítica', 'Tecnologia / Desenvolvimento'),
(55, 'Uma startup decide migrar de\r\numa arquitetura monolítica para uma\r\narquitetura de microservices. Qual é a\r\nprincipal vantagem dessa transição', 'Redução do tempo de carregamento do front-end da aplicação.', 'Facilitação da escalabilidade e do desenvolvimento independente de cada serviço.', 'Simplificação do processo de implantação com um único pipeline de CI/CD.', 'Menor complexidade na comunicação entre os diferentes módulos do sistema', 'b', 2024, '011', 'microservices', 'Tecnologia / Desenvolvimento'),
(56, 'Em React, qual das seguintes\r\nabordagens é a mais recomendada para\r\ngerenciar o estado em aplicações de grande\r\nescala?', 'Usar o useState em cada componente individual.', 'Centralizar o estado em um contexto global utilizando Context API.', 'Utilizar Redux para gerenciar o estado global da aplicação.', 'Manipular o estado diretamente no DOM sem usar o React', 'c', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(57, 'Qual é a principal diferença\r\nentre os sistemas de reatividade do Vue e do\r\nReact?\r\n', 'Vue utiliza um sistema de detecção de mudanças baseado em proxies, enquanto React utiliza um sistema de detecção de mudanças baseado em comparações superficiais (shallow comparison).', 'Vue requer a instalação de uma biblioteca externa para gerenciar reatividade, enquanto React possui um sistema nativo.', 'Em Vue, a reatividade é declarada explicitamente, enquanto em React ela é automática e não requer configuração.', 'React usa observáveis nativamente para gerenciar mudanças de estado, enquanto Vue não oferece suporte a observáveis.', 'a', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(58, 'No Angular, o que é um\r\ndecorator e qual é a sua função principal?\r\n', 'Um operador para transformar observáveis em promessas.', 'Um padrão de design utilizado para decorar componentes com funcionalidades adicionais.', 'Uma função que anota uma classe, método ou propriedade com metadados para determinar como eles devem ser tratados.', 'Um tipo de serviço que facilita a comunicação entre componentes.', 'c', 2024, '011', 'Angular', 'Tecnologia / Desenvolvimento'),
(59, 'Quando se utiliza v-if no\r\nVue.js, qual é o principal benefício em relação\r\nao uso de v-show', 'v-if é mais performático porque não renderiza o elemento no DOM até que a condição seja verdadeira.', ' v-if mantém o elemento no DOM, apenas alterando sua visibilidade, enquanto v-show remove e adiciona o elemento conforme a condição.', 'v-if é mais adequado para condições que mudam frequentemente, enquanto v-show é usado para condições estáticas.', 'v-if permite aplicar transições e animações, enquanto v-show não oferece suporte a essas funcionalidades.', 'a', 2024, '011', 'Vue.js', 'Tecnologia / Desenvolvimento'),
(60, 'Em React, qual das seguintes\r\npráticas é considerada uma má prática ao\r\nutilizar hooks?', 'Usar useEffect para executar uma função apenas quando o componente é montado.', 'Chamar um hook condicionalmente dentro de um componente funcional.', 'Dividir a lógica de um hook complexo em vários hooks menores.', 'Usar useMemo para evitar cálculos dispendiosos desnecessários.', 'b', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(61, 'No Angular, qual das seguintes\r\ncaracterísticas descreve corretamente o uso de\r\nservices?\r\n', 'Serviços no Angular são utilizados para criar componentes dinâmicos no DOM.', 'Serviços são injetáveis e usados para compartilhar lógica e dados entre componentes de forma eficiente.', 'Serviços são responsáveis por manipular diretamente o ciclo de vida de componentes.', 'Serviços devem ser registrados manualmente em cada componente que os utiliza.', 'B', 2024, '011', 'Angular', 'Tecnologia / Desenvolvimento'),
(62, 'Em Vue.js, qual é o propósito\r\ndo atributo key quando utilizado em listas\r\nrenderizadas com v-for?', 'Identificar elementos para que o Vue possa reutilizá-los eficientemente durante o re-render.', 'Definir o índice do elemento na lista para fácil acesso.', 'Especificar a ordem de renderização dos elementos na lista', 'Garantir que cada elemento seja renderizado como um novo componente, mesmo que seja semelhante a outros', 'a', 2024, '011', 'Vue.js', 'Tecnologia / Desenvolvimento'),
(63, 'Qual dos seguintes recursos é\r\nexclusivo do Angular em comparação com\r\nReact e Vue?', 'Componentes reutilizáveis.', 'Diretivas que alteram o comportamento dos elementos DOM.', 'Injeção de dependências nativa.', 'Suporte nativo para JSX.', 'c', 2024, '011', 'Angular', 'Tecnologia / Desenvolvimento'),
(64, 'Em React, quando é\r\nrecomendado usar o useContext em vez de\r\nprops para passar dados entre componentes?\r\n', 'Quando os dados precisam ser acessados profundamente na árvore de componentes', 'Quando os dados são utilizados apenas em componentes filhos imediatos.', 'Quando se deseja otimizar o desempenho do componente principal.', 'Quando é necessário evitar a re-renderização do componente pai.', 'a', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(65, 'No Vue.js, qual é a principal\r\nvantagem de usar o Vuex em uma aplicação\r\nde grande escala?\r\n', 'Aumentar a performance do Vue em dispositivos móveis.', 'Centralizar o estado em um único local para facilitar o gerenciamento de dados complexos', 'Facilitar a integração com bibliotecas de terceiros, como jQuery', 'Simplificar a criação de componentes de alta ordem.', 'c', 2024, '011', 'Vue.js', 'Tecnologia / Desenvolvimento'),
(66, 'Qual é a principal vantagem\r\nde utilizar a CLI (Command Line Interface)\r\nfornecida por frameworks como Angular, Vue\r\nou React?', 'Facilitar a inclusão de bibliotecas CSS externas.', 'Automatizar tarefas de configuração e scaffolding para iniciar rapidamente um novo projeto', 'Integrar automaticamente com plataformas de CI/CD sem configuração adicional.', 'Melhorar o desempenho de tempo de execução do aplicativo em produção.', 'B', 2024, '011', 'Frameworks', 'Tecnologia / Desenvolvimento'),
(67, 'Em React, qual é o efeito de\r\npassar uma função para o setState em vez de\r\num objeto?', 'Define o estado de forma síncrona.', 'Define o estado de forma assíncrona e permite o uso do estado anterior para calcular o novo.', 'Ignora o estado atual e substitui-o completamente pela função.', 'Permite a definição de múltiplos estados ao mesmo tempo.', 'A', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(68, 'No Angular, qual é o papel dos\r\nresolvers no gerenciamento de rotas?\r\n', 'Impedir o acesso a uma rota específica com base em regras de autorização.', 'Pré-carregar dados necessários para uma rota antes que ela seja ativada', 'Resolver conflitos de rotas em caso de duplicação de URLs', 'Aplicar animações personalizadas durante a transição entre rotas', 'a', 2024, '011', 'Angular', 'Tecnologia / Desenvolvimento'),
(69, 'Em Vue.js, o que acontece se\r\nvocê modificar o estado diretamente em vez\r\nde utilizar um método de mutação do Vuex?\r\n', 'O Vue não detectará a mudança e o DOM não será atualizado.', 'A mudança será detectada, mas pode causar comportamentos inesperados.', 'O Vuex lançará um erro, impedindo a alteração do estado.', 'A mudança será revertida na próxima renderização do componente.', 'B', 2024, '011', 'Vue.js', 'Tecnologia / Desenvolvimento'),
(70, 'No React, qual das seguintes\r\nalternativas descreve corretamente a função\r\nde higher-order components (HOCs)?', 'Componentes que são renderizados no servidor antes de serem enviados para o cliente.', 'Funções que permitem a criação de novos hooks personalizados.', 'Componentes que envolvem outros componentes para adicionar funcionalidades adicionais', 'Componentes que utilizam técnicas de memorização para otimizar a performance.', 'C', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(71, 'Qual é a principal razão para\r\nutilizar a técnica de lazy loading de módulos\r\nem Angular?', 'Melhorar a segurança da aplicação ao carregar módulos sob demanda.', 'Reduzir o tempo de carregamento inicial da aplicação, carregando módulos somente quando necessários', 'Simplificar a estrutura de rotas ao evitar a inclusão de módulos não utilizados.', 'Aumentar a eficiência no gerenciamento de estados com múltiplos módulos.', 'B', 2024, '011', 'Angular', 'Tecnologia / Desenvolvimento'),
(72, 'No contexto das práticas de\r\ndesign de UX e UI, assinale a opção que\r\napresenta corretamente uma justificativa para\r\na utilização dos Mapas de Calor (Heatmaps).\r\n', 'Garantem que o contraste entre texto e fundo seja suficiente em todas as partes do site ou do aplicativo.', 'Otimizam a carga de trabalho dos servidores, assegurando que o site ou o aplicativo tenha um desempenho melhor.', 'Obtêm insights visuais sobre como os usuários interagem com diferentes áreas da interface, identificando pontos de alto e baixo engajamento', 'Providenciam descrições textuais detalhadas para todos os elementos visuais, incluindo imagens e vídeos.', 'c', 2024, '011', 'Design de UX e UI', 'Tecnologia / Desenvolvimento'),
(73, 'Em relação ao\r\ndesenvolvimento front-end, analise as\r\nassertivas abaixo, assinalando V, se\r\nverdadeiras, ou F, se falsas.\r\n', 'Quando há necessidade de sobreposição de elementos, é possível controlar a ordem de camadas com a propriedade \"z-index\". Sendo assim, os elementos com essa propriedade que têm valores mais altos são exibidos mais à frente e com valores mais baixos são exibidos mais ao fundo.', ' Quando se trata da construção de um layout fluido, deve-se definir os elementos da página web com unidades de medida relativas, tais como pixels, ao invés de unidades absolutas como porcentagens.', 'A tag <div> foi descontinuada, e não é mais recomendada a sua utilização na construção de estruturas em HTML 5 por conta das tags semânticas.', 'Um layout responsivo é aquele que se ajusta para otimizar a exibição em dispositivos específicos através da definição de diferentes breakpoints.', 'D', 2024, '011', 'Front-end', 'Tecnologia / Desenvolvimento'),
(74, 'No React, qual das seguintes\r\npráticas é essencial para evitar problemas de\r\nperformance ao trabalhar com listas grandes?\r\n', 'Renderizar todos os itens de uma vez e confiar na capacidade do navegador para lidar com a quantidade de elementos.', 'Usar a prop key em cada item da lista para garantir uma renderização eficiente e correta.', 'Evitar o uso de map e recorrer a loops tradicionais para renderizar listas.', 'Separar cada item da lista em um componente de classe para melhorar a reutilização de código.', 'b', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(75, 'Qual das seguintes bibliotecas\r\né frequentemente usada em conjunto com\r\nReact para gerenciamento de side-effects,\r\ncomo chamadas assíncronas de API?\r\n', ' Vuex', 'NgRx', 'Redux-Saga', 'RxJS', 'c', 2024, '011', 'React', 'Tecnologia / Desenvolvimento'),
(76, 'Em Angular, qual é a função\r\nprincipal do Angular Router?', 'Controlar a renderização condicional de componentes.', 'Permitir a navegação entre diferentes vistas ou páginas na aplicação de forma dinâmica', 'Sincronizar estados globais entre componentes diferentes', 'Implementar mecanismos de segurança para proteger rotas', 'B', 2024, '011', 'Angular', 'Tecnologia / Desenvolvimento'),
(77, 'Durante o desenvolvimento de\r\num aplicativo móvel, a equipe de UX realiza\r\num teste de usabilidade. Qual é o principal\r\nobjetivo desse teste?', 'Avaliar o desempenho técnico do aplicativo em diferentes dispositivos.', 'Coletar dados de usuários para melhorar o design visual da interface.', 'Identificar problemas que os usuários enfrentam ao interagir com o aplicativo.', 'Medir o tempo de desenvolvimento necessário para implementar novas funcionalidades', 'c', 2024, '011', 'Teste de usabilidade', 'UX / UI Design'),
(78, 'Qual dos seguintes métodos é\r\nmais adequado para avaliar a usabilidade de\r\num site que já está em operação?', 'Revisão heurística feita por especialistas em usabilidade.', 'Análise de código para garantir a conformidade com padrões de acessibilidade.', 'Testes A/B para determinar qual layout atrai mais visitantes', 'Análise de logs do servidor para identificar falhas de performance', 'a', 2024, '011', 'Avaliação de usabilidade', 'UX / UI Design'),
(79, 'Uma empresa está\r\ndesenvolvendo uma nova plataforma de\r\ne-commerce e deseja garantir uma excelente\r\nexperiência do usuário (UX). Qual dos\r\nseguintes fatores é mais crítico para alcançar\r\nesse objetivo?\r\n', 'Adotar as cores da marca em todos os elementos da interface.', 'Implementar um processo de checkout simplificado e intuitivo.', 'Garantir que o site esteja disponível em vários idiomas.', 'Incluir animações complexas para impressionar os usuários', 'b', 2024, '011', 'Experiência do usuário (UX)', 'UX / UI Design'),
(80, 'No contexto da avaliação de\r\nusabilidade, o que significa o termo \"tempo de\r\ntarefa\"?\r\n', 'O tempo total que um usuário passa no site durante uma única sessão.', 'O tempo necessário para a equipe de desenvolvimento implementar uma nova funcionalidade.', 'O tempo que um usuário leva para completar uma tarefa específica, como finalizar uma compra.', 'O tempo de resposta do servidor ao processar uma solicitação de usuário', 'c', 2024, '011', 'Tempo de tarefa em UX', 'UX / UI Design'),
(81, 'Qual das seguintes métricas é\r\nmais utilizada para medir a eficiência de uma\r\ninterface do usuário (UI)?', 'Taxa de retorno dos usuários ao site.', 'Tempo de carregamento da página inicial.', 'Número de cliques necessários para concluir uma ação.', 'Número de visitantes únicos por dia.', 'c', 2024, '011', 'Métricas de eficiência em UI', 'UX / UI Design'),
(82, 'Durante a fase de\r\nprototipagem de um aplicativo, qual técnica é\r\nrecomendada para obter feedback inicial sobre\r\na usabilidade?', 'Lançar o protótipo diretamente para todos os usuários finais.', 'Realizar sessões de teste com grupos pequenos de usuários-alvo.', 'Distribuir pesquisas de opinião por e-mail para coletar feedback em massa.', 'Avaliar o protótipo com base em padrões de design populares.', 'B', 2024, '011', 'Prototipagem', 'UX / UI Design'),
(83, 'O que é uma \"persona\" em UX,\r\ne como ela é utilizada no processo de design?', 'Um avatar digital que representa a equipe de desenvolvimento em reuniões virtuais.', 'Um modelo de usuário fictício que ajuda a equipe a entender os objetivos e comportamentos dos usuários.', 'Uma técnica de programação usada para automatizar testes de usabilidade.', 'Um software especializado para criação de protótipos interativos.', 'B', 2024, '011', 'Persona em UX', 'UX / UI Design'),
(84, 'Qual é o propósito principal de\r\nrealizar testes de usabilidade com protótipos\r\nde baixa fidelidade?', 'Avaliar a performance do sistema sob carga pesada.', 'Identificar problemas de usabilidade de forma rápida e econômica', 'Testar a estabilidade do código antes do lançamento.', 'Otimizar a estética visual do produto antes do desenvolvimento final.', 'b', 2024, '011', 'Prototipagem', 'UX / UI Design'),
(85, 'Em um projeto de redesign de\r\num aplicativo, a equipe de UX utiliza mapas\r\nde calor (heatmaps) para entender o\r\ncomportamento dos usuários. Qual é a\r\nprincipal vantagem dessa ferramenta na\r\nanálise de dados?', 'Identificar os elementos mais clicados pelos usuários em uma interface.', 'Medir o desempenho técnico do aplicativo em diferentes dispositivos.', 'Avaliar a eficiência dos processos de back-end do aplicativo.', 'Determinar o tempo médio que os usuários passam no aplicativo.', 'a', 2024, '011', 'Mapas de calor (heatmaps)', 'UX / UI Design');
INSERT INTO `perguntas` (`id`, `pergunta`, `alternativa_a`, `alternativa_b`, `alternativa_c`, `alternativa_d`, `correta`, `ano_edital`, `numero_edital`, `temas`, `sub_temas`) VALUES
(86, 'Durante a análise de dados\r\ncoletados de um teste A/B, a equipe de UX\r\nobserva que a versão B de uma página teve\r\numa taxa de conversão significativamente\r\nmaior do que a versão A. Qual é a próxima\r\netapa recomendada?', 'Descartar a versão A e implementar permanentemente a versão B.', 'Realizar uma análise qualitativa para entender por que a versão B foi mais eficaz.', 'Reverter para a versão A até que mais dados sejam coletados.', 'Ignorar os resultados e testar uma nova versão C.', 'b', 2024, '011', 'Teste A/B', 'UX / UI Design'),
(87, 'Uma empresa de tecnologia\r\ndeseja melhorar a experiência do usuário em\r\nseu aplicativo móvel. Eles decidem analisar o\r\nfunil de conversão para identificar pontos de\r\nabandono. Qual dos seguintes é um exemplo\r\nde métrica do funil de conversão?', 'Número de downloads do aplicativo.', 'Porcentagem de usuários que completam o cadastro após iniciar o processo.', 'Taxa de crescimento do número de usuários ativos mensais.', 'Número de avaliações positivas na loja de aplicativos.', 'b', 2024, '011', 'Funil de conversão', 'UX / UI Design'),
(88, 'Em uma análise de dados UX,\r\nqual métrica seria mais útil para entender o\r\nnível de satisfação do usuário com uma nova\r\nfuncionalidade implementada em um\r\nsoftware?\r\n', 'Tempo médio gasto na funcionalidade', 'Taxa de rejeição ao utilizar a funcionalidade.', 'Net Promoter Score (NPS) coletado após o uso da funcionalidade.', 'Número de cliques necessários para acessar a funcionalidade.', 'c', 2024, '011', 'Net Promoter Score (NPS) em UX', 'UX / UI Design'),
(89, 'Qual é o principal benefício de\r\nutilizar análises preditivas em UX?', 'Melhorar a estética do design de interface com base em tendências passadas.', 'Antecipar comportamentos futuros dos usuários com base em dados históricos.', 'Automatizar a coleta de feedback dos usuários', 'Aumentar a taxa de cliques em anúncios dentro da aplicação.', 'b', 2024, '011', 'Análises preditivas', 'UX / UI Design'),
(90, 'Durante a análise de dados de\r\numa campanha de marketing digital, a equipe\r\nde UX percebe que a taxa de cliques (CTR) em\r\num botão importante é muito baixa. Qual seria\r\numa abordagem recomendada para resolver\r\nesse problema?\r\n', 'Aumentar o tamanho do botão e mudar sua cor para atrair mais atenção.', 'Remover o botão da página para simplificar o layout.', 'Aumentar a quantidade de texto na página para fornecer mais informações.', 'Reduzir a visibilidade do botão para focar em outros elementos.', 'a', 2024, '011', 'CTR – Call to Action', 'UX / UI Design'),
(91, 'Uma equipe de\r\ndesenvolvimento está criando um novo\r\naplicativo de e-commerce. Antes de iniciar o\r\ndesenvolvimento, eles criam um wireframe.\r\nQual é o principal objetivo de um wireframe?', 'Apresentar o design visual final do aplicativo.', 'Definir a estrutura básica e a organização dos elementos da interface', 'Implementar a lógica de backend para o aplicativo.', 'Realizar testes de usabilidade com usuários finais.', 'b', 2024, '011', 'Wireframe', 'UX / UI Design'),
(92, 'Durante a fase de design de\r\num aplicativo, o time de UX cria um protótipo\r\nde alta fidelidade. O que diferencia um\r\nprotótipo de alta fidelidade de um wireframe?', 'Um protótipo de alta fidelidade inclui interações realistas e detalhes visuais, enquanto um wireframe é mais simplificado e focado na estrutura.', 'Um protótipo de alta fidelidade é usado apenas para testes de backend, enquanto um wireframe é utilizado para testes de frontend.', 'Um protótipo de alta fidelidade é utilizado para documentação técnica, enquanto um wireframe é para documentação visual', 'Um protótipo de alta fidelidade não inclui elementos de navegação, enquanto um wireframe sim.', 'a', 2024, '011', 'wireframe', 'UX / UI Design'),
(93, 'Ao desenvolver um fluxo de\r\nnavegação para um site de serviços\r\nfinanceiros, qual é a principal preocupação\r\nque deve ser levada em consideração?', 'Garantir que todas as páginas tenham o mesmo número de cliques.', 'Criar um fluxo que minimize o número de passos necessários para concluir uma ação importante, como abrir uma conta.', 'Fazer com que cada página tenha o máximo de links possíveis para outras páginas.', 'Usar cores vibrantes em cada link para garantir que sejam notados.', 'b', 2024, '011', 'Fluxo de navegação', 'UX / UI Design'),
(94, 'Uma empresa está\r\ndesenvolvendo a interface de um novo\r\nsoftware de gestão. Para garantir uma boa\r\nusabilidade, eles estão focando no design do\r\nfluxo de navegação. Qual é o principal objetivo\r\ndo fluxo de navegação?', 'Criar uma experiência linear, onde os usuários devem seguir uma única rota através do software', 'Garantir que os usuários possam acessar facilmente as diferentes funcionalidades e áreas do software.', 'Implementar animações complexas para melhorar a estética do software.', 'Forçar os usuários a explorar cada funcionalidade antes de completar uma tarefa.', 'b', 2024, '011', 'Fluxo de navegação', 'UX / UI Design'),
(95, 'Durante o processo de design\r\nde um aplicativo móvel, a equipe cria\r\nwireframes para diferentes telas. Por que é\r\nimportante testar esses wireframes com\r\nusuários reais antes de avançar para o\r\ndesenvolvimento?\r\n', 'Para verificar se o código subjacente é compatível com a estrutura visual.', 'Para garantir que o design final esteja de acordo com as preferências de cor dos usuários.', 'Para identificar possíveis problemas de usabilidade e ajustá-los antes de investir em desenvolvimento.', 'Para determinar se as animações propostas são adequadas para o público-alvo.', 'b', 2024, '011', 'wireframes', 'UX / UI Design'),
(96, 'Uma equipe de UX está\r\ncriando um protótipo interativo para uma\r\nnova aplicação web. Qual é a principal\r\nvantagem de criar um protótipo interativo em\r\ncomparação a um wireframe estático?\r\n', 'Um protótipo interativo permite testar a lógica de negócios do aplicativo.', 'Um protótipo interativo pode ser usado diretamente como o produto final.', 'Um protótipo interativo permite que os usuários experimentem a navegação e a interação como fariam no produto final.', 'Um protótipo interativo requer menos tempo e recursos para ser criado do que um wireframe estático.', 'c', 2024, '011', 'wireframe', 'UX / UI Design'),
(97, 'Durante a criação da interface\r\nde um novo sistema de gerenciamento de\r\nprojetos, a equipe de design precisa decidir\r\ncomo organizar a barra de navegação. Qual\r\nabordagem é mais recomendada?', 'Organizar as opções de navegação com base na ordem alfabética', 'Priorizar as opções de navegação com base nas tarefas mais comuns e importantes para os usuários.', 'Criar uma barra de navegação com o máximo de opções possíveis para cobrir todas as funcionalidades.', 'Colocar as opções de navegação menos usadas em destaque para incentivar o uso', 'B', 2024, '011', 'Barra de navegação', 'UX / UI Design');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `perguntas`
--
ALTER TABLE `perguntas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `perguntas`
--
ALTER TABLE `perguntas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=98;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
