-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 30/06/2025 às 13:29
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `quiz_ppp`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `perguntas`
--

CREATE TABLE `perguntas` (
  `id` int(11) NOT NULL,
  `pergunta` text NOT NULL,
  `alternativa_a` text NOT NULL,
  `alternativa_b` text NOT NULL,
  `alternativa_c` text NOT NULL,
  `alternativa_d` text NOT NULL,
  `correta` char(1) NOT NULL,
  `ano_edital` int(11) NOT NULL DEFAULT 2024,
  `numero_edital` varchar(20) NOT NULL DEFAULT '001/2024',
  `temas` text NOT NULL DEFAULT 'Tema não especificado',
  `sub_temas` text NOT NULL DEFAULT 'Subtema não especificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `perguntas`
--

INSERT INTO `perguntas` (`id`, `pergunta`, `alternativa_a`, `alternativa_b`, `alternativa_c`, `alternativa_d`, `correta`, `ano_edital`, `numero_edital`, `temas`, `sub_temas`) VALUES
(1, 'Qual é a missão principal da ESP segundo o PPP?', 'Emitir diplomas para profissionais da saúde', 'Promover saúde com ações curativas', 'Contribuir para a formação e qualificação dos trabalhadores do SUS', 'Fiscalizar unidades de saúde', 'C', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(2, 'Segundo o\r\nPPP/ESP/CE-2024-2027, qual é a abordagem\r\npedagógica prioritária para o desenvolvimento\r\ndas ações formativas?', 'Ensino tradicional centrado na transmissão de conteúdo', 'Educação baseada em competências, com ênfase na aprendizagem ativa e contextualizada', 'Ensino exclusivamente teórico, sem práticas de campo.', 'Educação baseada em métodos expositivos e avaliações sumativas.', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(3, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é o papel da\r\navaliação institucional no processo de\r\nimplementação do projeto pedagógico?', 'Ser utilizada apenas para fins de classificação dos estudantes', 'Monitorar, avaliar e promover melhorias contínuas na formação e na gestão da escola', 'Ser realizada apenas ao final do ciclo de formação, sem impacto nas ações pedagógicas', 'Ser exclusiva para avaliação dos professores, sem envolver estudantes ou gestores.', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(4, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é o princípio\r\nnorteador para a elaboração das ações\r\npedagógicas na Escola de Saúde Pública do\r\nCeará?\r\n', 'A centralidade na transmissão de conhecimentos teóricos.', 'A integração entre teoria e prática, promovendo a formação contextualizada.', 'A priorização de atividades administrativas e burocráticas.', 'A segregação entre ensino, pesquisa e extensão, mantendo-os isolados', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(5, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual estratégia é\r\npriorizada para garantir a formação\r\ncontinuada dos docentes na Escola de Saúde\r\nPública do Ceará?', 'Oferecer cursos de curta duração sem relação com as demandas do SUS.', 'Promover programas de formação continuada alinhados às necessidades do sistema de saúde.', 'Manter os docentes em formação apenas no início da carreira, sem ações posteriores.', 'Priorizar atividades administrativas em detrimento do desenvolvimento profissional docente.', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(6, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é a principal\r\nestratégia para promover a integração entre\r\nensino, pesquisa e extensão na Escola de\r\nSaúde Pública do Ceará?', 'Manter essas atividades isoladas para garantir foco específico.', 'Promover ações integradas que articulam ensino, pesquisa e extensão de forma contínua e contextualizada.', 'Priorizar apenas a pesquisa, relegando o ensino e a extensão a um segundo plano', 'Limitar a participação dos estudantes nas atividades de extensão para evitar dispersão.', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(7, 'De acordo com o\r\nPPP/ESP/CE-2024-2027, qual é a abordagem\r\nprioritária para a formação de profissionais de\r\nsaúde na perspectiva de integralidade e\r\natenção básica?', ' Focar exclusivamente na formação técnica especializada, sem integração com a atenção básica.', 'Promover uma formação que valorize a integralidade, a atenção primária e a interdisciplinaridade, articulando teoria e prática.', 'Priorizar atividades administrativas e burocráticas, relegando a prática clínica.', 'Concentrar a formação apenas em ambientes acadêmicos, sem contato com os serviços de saúde.', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(8, 'Considerando a seção do\r\nPPP/ESP/CE-2024-2027 que trata da\r\navaliação institucional e seu papel no\r\naprimoramento contínuo da ESP-CE, qual das\r\nseguintes abordagens metodológicas\r\ndemonstra maior aderência aos princípios de\r\numa avaliação formativa e participativa,\r\nconforme preconizado no documento?\r\n', 'Aplicação de questionários padronizados ao final de cada ciclo formativo, com foco em indicadores quantitativos de desempenho discente.', 'Implementação de um sistema de acompanhamento individualizado do progresso dos estudantes, baseado em portfólios e autoavaliações supervisionadas.', 'Realização de reuniões periódicas com representantes de diferentes segmentos da comunidade acadêmica para análise qualitativa dos processos e resultados, culminando na elaboração de planos de melhoria consensuais.', 'Utilização de provas objetivas somativas, com o objetivo de classificar os estudantes e identificar lacunas de aprendizagem em nível macroinstitucional.', 'c', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(9, 'O PPP/ESP/CE-2024-2027\r\nenfatiza a importância da integração\r\ncurricular e da interdisciplinaridade como\r\neixos estruturantes dos processos formativos.\r\nQual das seguintes iniciativas pedagógicas\r\nrepresenta a aplicação mais efetiva desses\r\nprincípios?\r\n', ' Organização dos conteúdos disciplinares em módulos estanques, com avaliações separadas para cada disciplina.', 'Desenvolvimento de projetos de intervenção na realidade social e de saúde, envolvendo diferentes áreas do conhecimento e a participação ativa dos estudantes.', 'Utilização de metodologias ativas de ensino-aprendizagem em disciplinas específicas, mantendo a estrutura curricular tradicional', 'Oferta de disciplinas eletivas que abordam temas transversais, permitindo que os estudantes complementem sua formação de forma individualizada.', 'b', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(10, 'Considerando o eixo\r\nestratégico de &quot;Gestão e Avaliação da\r\nFormação&quot; presente no\r\nPPP/ESP/CE-2024-2027, qual das seguintes\r\nações representa a abordagem mais alinhada\r\ncom a proposta de avaliação formativa e\r\ncontinuada dos processos educativos, visando\r\no aprimoramento constante das ofertas\r\nformativas da Escola?\r\n', 'A aplicação de provas objetivas ao final de cada módulo ou curso, com o objetivo de classificar os participantes e identificar aqueles que atingiram o desempenho mínimo esperado.', 'A implementação de um sistema de coleta de feedback dos participantes ao final de cada atividade educativa, utilizando questionários padronizados com foco na satisfação com o conteúdo e os facilitadores.', 'O desenvolvimento de instrumentos de avaliação diversificados que incluam a autoavaliação dos participantes, a avaliação por pares, a análise de portfólios e a observação de práticas, integrados ao longo do processo formativo para fornecer insights para ajustes pedagógicos.', 'A realização de avaliações externas periódicas por órgãos competentes, com o objetivo de certificar a qualidade das ofertas formativas da Escola em relação a padrões nacionais e internacionais.', 'c', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(11, 'Considerando o eixo\r\nestratégico de &quot;Gestão e Avaliação da\r\nFormação&quot; presente no\r\nPPP/ESP/CE-2024-2027, qual das seguintes\r\nações representa a abordagem mais alinhada\r\ncom a proposta de avaliação formativa e\r\ncontinuada dos processos educativos, visando\r\no aprimoramento constante das ofertas\r\nformativas da Escola?\r\n', 'A aplicação de provas objetivas ao final de cada módulo ou curso, com o objetivo de classificar os participantes e identificar aqueles que atingiram o desempenho mínimo esperado.', 'A implementação de um sistema de coleta de feedback dos participantes ao final de cada atividade educativa, utilizando questionários padronizados com foco na satisfação com o conteúdo e os facilitadores.', 'O desenvolvimento de instrumentos de avaliação diversificados que incluam a autoavaliação dos participantes, a avaliação por pares, a análise de portfólios e a observação de práticas, integrados ao longo do processo formativo para fornecer insights para ajustes pedagógicos.', 'A realização de avaliações externas periódicas por órgãos competentes, com o objetivo de certificar a qualidade das ofertas formativas da Escola em relação a padrões nacionais e internacionais.', 'c', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(12, 'Considerando o eixo\r\nestratégico de &quot;Gestão e Avaliação da\r\nFormação&quot; presente no\r\nPPP/ESP/CE-2024-2027, qual das seguintes\r\nações representa a abordagem mais alinhada\r\ncom a proposta de avaliação formativa e\r\ncontinuada dos processos educativos, visando\r\no aprimoramento constante das ofertas\r\nformativas da Escola?\r\n', 'A aplicação de provas objetivas ao final de cada módulo ou curso, com o objetivo de classificar os participantes e identificar aqueles que atingiram o desempenho mínimo esperado.', 'A implementação de um sistema de coleta de feedback dos participantes ao final de cada atividade educativa, utilizando questionários padronizados com foco na satisfação com o conteúdo e os facilitadores.', 'O desenvolvimento de instrumentos de avaliação diversificados que incluam a autoavaliação dos participantes, a avaliação por pares, a análise de portfólios e a observação de práticas, integrados ao longo do processo formativo para fornecer insights para ajustes pedagógicos.', 'A realização de avaliações externas periódicas por órgãos competentes, com o objetivo de certificar a qualidade das ofertas formativas da Escola em relação a padrões nacionais e internacionais.', 'c', 2024, '001/2024', 'Tema não especificado', 'Subtema não especificado'),
(13, 'Considerando a Lei Federal nº\r\n8.080/1990, que regula as ações e serviços de\r\nsaúde no Brasil, assinale a afirmativa que\r\nreflete um dos objetivos fundamentais do\r\nSistema Único de Saúde (SUS)', 'priorizar a assistência direta aos indivíduos, com ações pontuais e não prioritárias de prevenção e promoção da saúde.', 'o grande foco é a recuperação da saúde, com destinação de poucos esforços para a prevenção de doenças e promoção da saúde.', 'a identificação dos fatores determinantes da saúde ocorre de forma contínua sem a inclusão de formulação de políticas de saúde em seus objetivos.', 'oca em garantir a assistência às pessoas por meio de ações abrangentes de promoção, proteção e recuperação da saúde, integrando tanto serviços assistenciais quanto ações preventivas', 'D', 2024, '08/2024', 'Lei Federal nº 8.080/1990', 'Subtema não especificado'),
(14, '“De acordo com os princípios e\r\ndiretrizes do SUS, assinale a alternativa que\r\nmelhor se enquadra na definição a seguir:\r\n“Significa garantir que todos tenham acesso\r\nigualitário aos serviços de saúde, priorizando\r\nas necessidades daqueles que mais precisam,\r\nsem discriminação ou favorecimento injusto.\r\nIsso implica em distribuir recursos de forma\r\njusta e proporcionar atenção integral e\r\nuniversal, considerando as diferenças\r\nindividuais e coletivas da população\r\nbrasileira.”\r\n', 'equidade.', 'integralidade.', 'resolutividade.', 'universalidade.', 'A', 2024, '008', 'Princípios do SUS – Equidade', 'Subtema não especificado'),
(15, 'A hierarquização no Sistema de\r\nSaúde faz parte de um princípio básico. Nesse\r\nsentido, assinale a alternativa que descreva a\r\nhierarquia do Sistema Único de Saúde (SUS).', 'deve existir uma análise da idade dos pacientes para promover os serviços e realizar o atendimento com base na prioridade.', 'as ações e os serviços oferecidos pelo sistema devem respeitar os níveis de complexidade: primário, secundário e terciário.', 'a hierarquia discorre sobre os médicos possuírem um nível de superioridade em relação aos enfermeiros, e que a decisão do médico deve sempre prevalecer.', 'as ações e os serviços oferecidos pelo sistema não devem respeitar os níveis de complexidade, ou seja, o paciente pode ser atendido em qualquer nível de atenção independentemente da sua necessidade.', 'B', 2024, '008/2024', 'Organização do SUS – Níveis de Atenção e Hierarquização', 'Subtema não especificado'),
(16, 'Um grupo de profissionais,\r\ninteressados em ingressar na Escola de Saúde\r\nPública do Ceará (ESP/Ce), estava discutindo\r\ncomo esta instituição foi criada. Dentre as\r\nopções abaixo, marque a correta.\r\nA ESP/Ce foi criada:', 'em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Universidade Federal do Ceará (UFC) e da Universidade Estadual do Ceará (UECE).', 'em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Federal do Ceará (UFC).', 'em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Estadual do Ceará (UECE)', 'em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Escola Nacional de Saúde Pública (ENSP)', 'B', 2024, '008/2024', 'História da ESP/CE', 'Subtema não especificado'),
(17, 'Estudando o histórico da\r\nEscola de Saúde Pública do Ceará (ESP/Ce),\r\num grupo de profissionais percebeu que o\r\nobjetivo do projeto de sua criação foi:', 'ser uma instituição destinada para a formação dos servidores da Secretaria da Saúde do Estado do Ceará (SESA) nos aspectos relacionados à saúde pública e do SUS.', 'proporcionar aos profissionais da saúde o acesso à formação e capacitação de modo a desenvolver as competências para a operacionalização das suas atividades no âmbito do SUS.', 'ser uma instituição acadêmica vinculada à Secretaria da Saúde do Estado do Ceará (SESA) para a formação e qualificação de seus servidores, oportunizando cursos de mestrado e doutorado.', 'proporcionar aos profissionais da saúde o acesso à graduação e educação continuada de modo a desenvolver os conhecimentos necessários para a operacionalização das atividades no âmbito do SUS.', 'B', 2024, '008/2024', 'Missão e Objetivo Institucional da ESP/CE', 'Subtema não especificado'),
(20, 'Dois autores fundamentam os\r\npressupostos filosóficos do Projeto Político\r\nPedagógico da ESP/Ce. São eles:', 'John Dewey e Paulo Freire', 'Jerome Bruner e Lev Vygotsky', 'Maria Montessori e Paulo Freire', 'Anísio Teixeira e Darcy Ribeiro', 'A', 2024, '008/2024', 'PPP da ESP/CE', 'Subtema não especificado'),
(21, 'O PPP vigente da ESP/CE e,\r\ndisponível em sua página, estabelece que uma\r\nde suas premissas educacionais é orientar e\r\nbasear na comunidade o currículo de seus\r\nProgramas. Isso significa que:', 'durante a elaboração da justificativa do currículo do Programa é obrigatória a presença de representantes da comunidade e profissionais de saúde que atuam em ambiente comunitário.', 'no desenho do currículo do Programa devem ser levadas em conta as necessidades da comunidade e previstas atividades educacionais no ambiente comunitário.', ' a maior parte da execução do Programa seja em ambientes comunitários e serviços de atenção básica à saúde.', 'o desenho do currículo seja feito por especialistas em saúde comunitária ou em saúde coletiva.', 'b', 2024, '009/2024', 'PPP da ESP/CE', 'Subtema não especificado'),
(22, 'Alguns professores da ESP/CE\r\nforam encarregados para elaborar um Curso\r\nde Especialização. Dentre as alternativas\r\nabaixo, assinale a que melhor expressa,\r\ncronologicamente, algumas das etapas da\r\nelaboração do currículo do curso, segundo\r\norientações do PPP vigente:', 'análise da potencial clientela, elaboração da justificativa do curso, elaboração das competências e objetivos de aprendizagem, construção da matriz curricular.', 'definição dos conteúdos, elaboração dos objetivos de aprendizagem, definição das competências a serem desenvolvidas e escolha dos métodos de ensino e avaliação.', 'elaboração da justificativa do curso, análise da potencial clientela, elaboração das competências e objetivos de aprendizagem, escolha dos métodos de ensino e avaliação.', 'definição das competências a serem desenvolvidas, definição dos conteúdos, elaboração dos objetivos de aprendizagem e escolha dos métodos de ensino e avaliação.', 'c', 2024, '009/2024', 'PPP da ESP/CE', 'Subtema não especificado'),
(23, 'O coordenador de um\r\nPrograma de Especialização da ESP/CE\r\nprocurou assessoria educacional para utilizar a\r\nAprendizagem Baseada em Problemas\r\n(Problem Based Learning – PBL) como\r\nmetodologia ativa no curso.\r\nSegundo o PPP vigente da ESP/CE, o PBL:', ' é uma metodologia ativa de aprendizagem baseada na análise e resolução de problemas, em pequenos grupos, com o suporte de um facilitador.', ' é uma metodologia ativa de aprendizagem na qual o professor/facilitador dá aulas em pequenos grupos utilizando uma situação-problema.', 'também conhecido no Brasil como Metodologia da Problematização, utiliza sete passos durante os grupos tutoriais.', 'é uma metodologia ativa de aprendizagem que utiliza como técnica de ensino o Arco de Maguerez.', 'a', 2024, '009/2024', 'PPP da ESP/CE', 'Subtema não especificado'),
(24, 'Estudando o histórico da\r\nEscola de Saúde Pública do Ceará (ESP/Ce),\r\num grupo de profissionais percebeu que o\r\nobjetivo do projeto de sua criação foi:', 'Ser uma instituição destinada para a formação dos servidores da Secretaria da Saúde do Estado do Ceará (SESA) nos aspectos relacionados à saúde pública e do SUS.', 'Proporcionar aos profissionais da saúde o acesso à formação e capacitação de modo a desenvolver as competências para a operacionalização das suas atividades no âmbito do SUS.', 'Ser uma instituição acadêmica vinculada à Secretaria da Saúde do Estado do Ceará (SESA) para a formação e qualificação de seus servidores, oportunizando cursos de mestrado e doutorado.', 'Proporcionar aos profissionais da saúde o acesso à graduação e educação continuada de modo a desenvolver os conhecimentos necessários para a operacionalização das atividades no âmbito do SUS.', 'a', 2024, '011/2024', 'PPP da ESP/CE', 'Subtema não especificado'),
(25, 'Considerando o processo de\r\ndesenvolvimento histórico da Escola de Saúde\r\nPública do Ceará - ESP/CE, marque a assertiva\r\ncorreta.', ' Foi criada em 1990, a partir da sanção da Lei nº 12.140, sob a forma de autarquia, vinculada à Secretaria de Saúde do Estado do Ceará', 'Compõe a Rede das Escolas Técnicas do SUS (RET-SUS) e está entre as 20 escolas existentes no país. Isso porque, desde a sua criação, tem como um de seus focos de atenção a formação na área da Educação básica.', 'Outro marco histórico foi o lançamento da revista Cadernos ESP, uma publicação anual, voltada para atender as necessidades do SUS e divulgar pesquisas em saúde coletiva e educação, no âmbito estadual.', 'Foi estabelecida com o propósito de promover ações voltadas à pesquisa, informação, documentação em saúde pública, educação continuada, capacitação e aperfeiçoamento dos profissionais do Sistema Único de Saúde estadual.', 'd', 2024, '011/2024', 'História da ESP/CE', 'Subtema não especificado'),
(26, 'A missão, visão e os valores\r\norganizacionais da ESP/CE foram revistos e\r\natualizados durante o Planejamento\r\nEstratégico. Desta forma, depreende-se que,\r\natualmente, representam a intenção\r\nestratégica, o pensamento sistêmico que\r\ninfluenciam e direcionam a execução das\r\nações da Instituição. Logo:', 'Tem como missão promover o desenvolvimento de excelência da força de trabalho em Saúde por meio da Educação Permanente, apoiado pela ciência, inovação e tecnologia, visando o fortalecimento do SUS e a melhoria da qualidade de vida das pessoas.', 'Tem por missão promover a educação, o conhecimento e a inovação, contribuindo para a saúde individual e coletiva, além da melhoria da qualidade de vida e felicidade das pessoas', 'Tem como visão o comprometimento com o SUS; Eficiência e sustentabilidade; Ética; Valores Humanização; Inclusão e diversidade; Inovação e conhecimento; Transparência; Valorização das pessoas', 'Tem como valores a busca pelo reconhecimento da excelência na educação e formação de qualificação da força de trabalho para o Sistema Único de Saúde.', 'a', 2024, '011/2024', 'Missão e Objetivo Institucional da ESP/CE', 'Subtema não especificado'),
(27, 'A missão, visão e os valores\r\norganizacionais da ESP/CE foram revistos e\r\natualizados durante o Planejamento\r\nEstratégico. Desta forma, depreende-se que,\r\natualmente, representam a intenção\r\nestratégica, o pensamento sistêmico que\r\ninfluenciam e direcionam a execução das\r\nações da Instituição. Logo:', 'Tem como missão promover o desenvolvimento de excelência da força de trabalho em Saúde por meio da Educação Permanente, apoiado pela ciência, inovação e tecnologia, visando o fortalecimento do SUS e a melhoria da qualidade de vida das pessoas.', 'Tem por missão promover a educação, o conhecimento e a inovação, contribuindo para a saúde individual e coletiva, além da melhoria da qualidade de vida e felicidade das pessoas', 'Tem como visão o comprometimento com o SUS; Eficiência e sustentabilidade; Ética; Valores Humanização; Inclusão e diversidade; Inovação e conhecimento; Transparência; Valorização das pessoas', 'Tem como valores a busca pelo reconhecimento da excelência na educação e formação de qualificação da força de trabalho para o Sistema Único de Saúde.', 'a', 2024, '011/2024', 'Missão e Objetivo Institucional da ESP/CE', 'Subtema não especificado'),
(28, 'Em dezembro de 2020, com\r\nbase no diagnóstico situacional da saúde da\r\npopulação cearense e da estrutura dos\r\nequipamentos da Rede Sesa, foi lançado pela\r\nESP/CE um projeto com uma de suas\r\nfinalidades regionalizar as vagas dos\r\nProgramas de Residências em Saúde,\r\nfortalecendo as Redes de Atenção à Saúde de\r\nacordo com as necessidades regionais. Que\r\nação foi essa?', 'Programa de Valorização dos Supervisores de Residências em Saúde.', 'Projeto Ampliares.', ' Projeto de Interiorização de Residências em Saúde (PIRS).', 'Programa de Valorização dos Preceptores de Residências em Saúde', 'b', 2024, '011/2024', 'PIRS', 'Subtema não especificado'),
(29, 'O Decreto nº 35.344, de 22\r\nde junho de 2023, e o Decreto nº 35.750, de\r\n10 de novembro de 2023, alteram a estrutura\r\norganizacional da ESP/CE, que passou a ser\r\ncomposta por:', 'Superintendência, Assessorias, Diretorias e Gerências.', 'Diretoria Geral, Coordenadorias, Assessorias e Gerências.', 'Superintendência, Diretorias, Assessorias e Núcleos.', 'Diretoria Geral, Coordenadorias, Assessorias e Centros.', 'a', 2024, '011/2024', 'Estrutura organizacional da ESP/CE – decretos de 2023', 'Subtema não especificado'),
(30, 'Um grupo de profissionais,\r\ninteressados em ingressar na Escola de Saúde\r\nPública do Ceará (ESP/Ce), estava discutindo\r\ncomo esta instituição foi criada. Dentre as\r\nopções abaixo, marque a correta. A ESP/Ce foi\r\ncriada:', 'Em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Universidade Federal do Ceará (UFC) e da Universidade Estadual do Ceará (UECE).', 'Em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Federal do Ceará (UFC)', 'Em 1992 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Universidade Estadual do Ceará (UECE)', 'Em 1993 a partir de uma proposta de um grupo de trabalho formado por técnicos da Secretaria da Saúde do Estado do Ceará (SESA) e da Escola Nacional de Saúde Pública (ENSP).', 'b', 2024, '011/2024', 'História da ESP/CE', 'Subtema não especificado'),
(31, 'Em um contexto de\r\ndesenvolvimento web, considerando o uso de\r\nframeworks, qual das opções descreve\r\ncorretamente uma vantagem do seu uso?', 'Aumento da complexidade do código devido à padronização forçada.', 'Diminuição da produtividade da equipe de desenvolvimento devido à curva de aprendizado.', 'Aumento das opções de personalização devido à flexibilidade oferecida pelo framework.', 'Facilidade na implementação de funcionalidades comuns devido à reutilização de código e convenções estabelecidas.', 'd', 2024, '011/2024', '(Tecnologia / Desenvolvimento)', 'Subtema não especificado'),
(32, 'Em um cenário de rápido\r\ncrescimento tecnológico e demandas cada vez\r\nmais complexas, os frameworks de\r\narquitetura surgem como resposta à\r\nnecessidade de padronização e organização no\r\ndesenvolvimento de sistemas distribuídos,\r\nvisando facilitar a escalabilidade, a\r\ninteroperabilidade e a manutenção em\r\nambientes heterogêneos e dinâmicos.\r\nAssinale a opção que indica características de\r\num framework de arquitetura', 'Os frameworks de arquitetura são estruturas conceituais ou um conjunto de estruturas, para desenvolvimento, implementação e manutenção de uma arquitetura.', 'Esses frameworks ampliam a complexidade do desenvolvimento incremental da arquitetura e descrevem convenções e práticas de arquitetura em comunidades e domínios de aplicação.', 'Esses frameworks obrigatoriamente incluem descrições de aspectos de interesse e escopo da arquitetura a ser desenvolvida.', 'Os frameworks de arquitetura podem ser usados em contexto específico de processos que facilitam a comunicação entre projetos.', 'a', 2024, '011/2024', '(Tecnologia / Desenvolvimento)', 'Subtema não especificado'),
(33, 'O desenvolvimento orientado a\r\ntestes (TDD):', ' é um conjunto de técnicas que se associam ao X P (extreme programming) para o desenvolvimento incremental do código que se inicia com os testes.', 'agrega um conjunto de testes de integração para avaliar a interconexão dos componentes do software com as aplicações a ele relacionadas.', ' avalia o desempenho do desenvolvimento de sistemas verificando se o volume de acessos/transações está acima da média esperada.', 'averiguar se o sistema atende aos requisitos de desempenho verificando se o volume de acessos/transações se mantém dentro do esperado.', 'a', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - Desenvolvimento orientado a testes (TDD)', 'Subtema não especificado'),
(34, 'Em um sistema baseado em\r\nmicroservices, qual das seguintes opções é\r\numa desvantagem em relação a uma\r\narquitetura monolítica?', 'A dificuldade em escalar a aplicação horizontalmente', 'A complexidade na gestão e monitoramento de múltiplos serviços independente', 'A necessidade de reescrever todo o código para introduzir uma nova funcionalidade.', 'A dependência de um único banco de dados centralizado para todas as operações.', 'B', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - microservices', 'Subtema não especificado'),
(35, 'O código limpo, ou clean code,\r\né um estilo de programação que enfatiza a\r\nlegibilidade, a facilidade de manutenção e a\r\neficiência do código. O objetivo é:', ' escrever código que seja fácil de entender e complexo de editar o que facilita a colaboração entre membros da equipe e reduz a incidência de problemas (bugs).', ' escrever código que seja fácil de entender e fácil de editar o que facilita a colaboração entre membros da equipe, no entanto aumenta a incidência de problemas (bugs).', ' escrever código que seja complexo de entender e de editar para evitar a incidência de problemas (bugs).', 'O objetivo é escrever código que seja fácil de entender e modificar, o que facilita a colaboração entre membros da equipa e reduz a incidência de problemas (bugs).', 'D', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - Código Limpo/ Clean Code', 'Subtema não especificado'),
(36, 'Em relação aos princípios de\r\nClean Code, qual das seguintes práticas é mais\r\nimportante para garantir que o código seja\r\nlegível e fácil de manter por outros\r\ndesenvolvedores?', 'Utilizar nomes de variáveis e funções que descrevam claramente sua finalidade e comportamento.', ' Escrever o código de forma a minimizar o número de linhas, mesmo que a legibilidade seja comprometida.', ' Incluir comentários extensivos para explicar cada linha de código.', 'Focar em otimização prematura para melhorar o desempenho em detrimento da clareza do código.', 'A', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - Código Limpo/ Clean Code', 'Subtema não especificado'),
(37, 'Em relação a segurança da\r\nlinguagem javascript no lado do cliente na\r\ncondição padrão de defesa dos navegadores\r\nweb, é permitido:', 'gravar arquivos arbitrários no computador do cliente', 'configurar a propriedade value do HTML file upload.', 'listar diretórios arbitrários no computador do cliente.', 'fechar janelas do navegador abertas pelo javascript.', 'D', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - JavaScript', 'Subtema não especificado'),
(38, 'Na linguagem javascript, são\r\nutilizadas palavras em um mecanismo para\r\ntratamento de exceções:', 'try, catch e except', 'catch, throw e except', 'try e except', 'try, catch e finally.', 'D', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - JavaScript', 'Subtema não especificado'),
(39, 'Na linguagem JavaScript\r\nquando o valor de uma variável é declarado,\r\nmas ela não possui nenhum valor concreto\r\narmazenado, como por exemplo em um\r\nelemento array que não existe, é retornado:', ' string 0.', 'objeto global.', ' Null', 'indefinido.', 'd', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - JavaScript', 'Subtema não especificado'),
(40, 'Sobre a tecnologia WEB do\r\nJavascript (JS), para inserir códigos JS em um\r\ndocumento HTML, é necessário o uso de uma\r\ntag específica para isso. A qual tag abaixo o\r\ntrecho se refere?', '<html> conteúdo </html>', '<head> conteúdo </head>', '<inputJS> conteúdo </ inputJS >', '<script> conteúdo </script>', 'd', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - JavaScript', 'Subtema não especificado'),
(41, 'Para que uma API seja\r\nreconhecida como RESTful, ela deve atender a\r\nalguns critérios adicionais aos princípios\r\nREST. Entre esses critérios está a interface\r\nuniforme, que pode ser obtida', ' pela garantia de que será fornecido o mesmo resultado pelo servidor, independentemente de quantas vezes for requisitado recurso.', 'pelas informações completas e necessárias fornecidas pelo cliente para que o servidor entenda e processe a requisição.', 'pela identificação de recursos em requisições de forma única', ' pelos depósitos temporários (cache) dos resultados retornados pelo servidor', 'c', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - RESTful', 'Subtema não especificado'),
(42, 'Nos métodos ágeis XP e Scrum,\r\nas entregas de partes funcionais do projeto\r\nsão divididas em ciclos, geralmente\r\ncompreendidos no período de 1 a 4 semanas.\r\nEstes ciclos denominam-se, respectivamente,\r\n', 'iterações e sprint.', 'reunião de planejamento e backlog.', 'período de entrega e reunião de revisão.', 'backlog e planejamento da produção.', 'a', 2024, '011/2024', '(Tecnologia / Desenvolvimento) - Métodos ágeis', 'Subtema não especificado'),
(43, 'Assinale a alternativa que\r\napresenta corretamente uma metodologia ágil\r\npara a gestão e planejamento de projetos de\r\nsoftware.', 'Scrum', 'Ciclo de Vida', 'RUP – Rational Unified Process', 'Ferramentas CASE', 'a', 2024, '011', '(Tecnologia / Desenvolvimento) - Métodos ágeis', 'Subtema não especificado'),
(44, 'Assinale a alternativa correta\r\nconsiderando as responsabilidades e os papéis\r\nna metodologia SCRUM.', 'O responsável por gerenciar o Product Backlog (garantindo que esteja visível para todos), gerar e disseminar os requisitos do projeto, assim como o plano para as entregas sucessivas, priorizando os resultados que trarão maior valor agregado ao projeto, é o Product Owner.', 'O responsável por implementar o método Scrum, assim como por ensiná-lo a todos os envolvidos nos projetos e assegurar que todos sigam as suas regras e práticas é denominado Time Scrum.', 'O grupo de desenvolvedores que é coletivamente responsável pelo sucesso de cada iteração e do projeto como um todo é conhecido como Scrum Masters.', 'O grupo de gerentes com responsabilidade de avaliar os custos do projeto é denominado Scrum Cost.', 'a', 2024, '011', '(Tecnologia / Desenvolvimento) - Métodos ágeis', 'Subtema não especificado'),
(45, 'Durante uma revisão de código\r\n(code review), qual é o principal objetivo ao\r\nrevisar a lógica implementada por um\r\ndesenvolvedor?', 'Identificar inconsistências visuais na interface do usuário', 'Verificar se o código segue os padrões de nomenclatura da equipe', 'Garantir que a lógica do código seja correta e eficiente, evitando bugs.', 'Avaliar a complexidade das ferramentas de automação utilizadas', 'c', 2024, '011', '(Tecnologia / Desenvolvimento) - Métodos ágeis', 'Subtema não especificado'),
(46, 'Qual tipo de teste de software\r\né realizado para garantir que uma única\r\nfunção ou método do código esteja\r\nfuncionando corretamente, de forma isolada?\r\n', 'Teste de integração', 'Teste funcional', 'Teste unitário', 'Teste de desempenho', 'c', 2024, '011', '(Tecnologia / Desenvolvimento) - testes (TDD)', 'Subtema não especificado'),
(47, 'Em um projeto de software, o\r\nteste de integração é realizado para:', 'Verificar o desempenho do sistema sob carga extrema.', 'Avaliar a funcionalidade de interfaces gráficas do usuário.', 'Garantir que diferentes módulos do sistema funcionem bem juntos.', 'Testar individualmente as menores unidades de código.', 'c', 2024, '011', '(Tecnologia / Desenvolvimento) - testes (TDD)', 'Subtema não especificado'),
(48, 'Quando um time de QA realiza\r\ntestes funcionais em um software, qual é o\r\nprincipal foco desses testes?\r\n', 'Avaliar a usabilidade da interface do usuário.', 'Verificar a performance do sistema sob condições de pico.', 'Garantir que as funcionalidades do sistema correspondam aos requisitos especificados', 'Analisar o consumo de recursos de hardware durante a execução do software.', 'c', 2024, '011', '(Tecnologia / Desenvolvimento) - testes (TDD)', 'Subtema não especificado'),
(49, 'Durante a fase de testes de\r\ndesempenho, qual aspecto do software é mais\r\nfrequentemente avaliado?\r\n', 'A capacidade do software de executar todas as funcionalidades planejadas.', 'A velocidade e estabilidade do software sob diferentes cargas de uso.', 'A integração correta entre diferentes módulos e componentes.', 'A clareza e a qualidade do código fonte escrito pelos desenvolvedores.', 'B', 2024, '011', '(Tecnologia / Desenvolvimento) - testes (TDD)', 'Subtema não especificado'),
(50, 'Uma empresa de tecnologia\r\nestá desenvolvendo um novo aplicativo de\r\ncomércio eletrônico e está considerando\r\nutilizar uma arquitetura monolítica. Qual das\r\nseguintes afirmações melhor descreve uma\r\ncaracterística dessa abordagem?', 'Cada funcionalidade do aplicativo é desenvolvida e mantida como um serviço independente.', 'Todo o código da aplicação é integrado em um único código base, facilitando a implantação.', 'A escalabilidade horizontal é simples, permitindo o crescimento modular do sistema.', 'A comunicação entre componentes ocorre exclusivamente por meio de APIs RESTful.', 'b', 2024, '011', '(Tecnologia / Desenvolvimento) - Arquitetura monolítica', 'Subtema não especificado'),
(51, 'Uma startup decide migrar de\r\numa arquitetura monolítica para uma\r\narquitetura de microservices. Qual é a\r\nprincipal vantagem dessa transição', 'Redução do tempo de carregamento do front-end da aplicação.', 'Facilitação da escalabilidade e do desenvolvimento independente de cada serviço.', 'Simplificação do processo de implantação com um único pipeline de CI/CD.', 'Menor complexidade na comunicação entre os diferentes módulos do sistema', 'b', 2024, '011', '(Tecnologia / Desenvolvimento) - microservices', 'Subtema não especificado');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `perguntas`
--
ALTER TABLE `perguntas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `perguntas`
--
ALTER TABLE `perguntas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
